# Generated by Django 5.1.7 on 2025-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
